# Generated by Django 2.2.1 on 2019-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190530_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.AddField(
            model_name='post',
            name='article_tags',
            field=models.ManyToManyField(related_name='tags_for_article', to='news.Tag'),
        ),
    ]
