# Generated by Django 2.2.1 on 2019-06-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190601_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
    ]
