# Generated by Django 2.2.1 on 2019-06-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
