# Generated by Django 2.2.1 on 2019-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190601_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=12, max_length=128),
            preserve_default=False,
        ),
    ]
